### ISSUE TITLE
NoMethodError in pure ruby

### ISSUE THREAD

**Issue by micat** [aisaac-lab/line-bot#4]
Given I installed the gem and have following file.

```
require 'line/bot/client'

client = Line::Bot::Client.new do |config|
  # ommited
end

puts client.get_profiles([client.channel_mid])
```

The script raises NoMethodError.

```
$ ruby test.rb
/path/to/gems/line-bot-0.0.4/lib/line/bot/request.rb:14:in `initialize': undefined method `URI' for #<Line::Bot::Request:0x007fd2db903188> (NoMethodError)
    from /path/to/gems/line-bot-0.0.4/lib/line/bot/api.rb:24:in `new'
    from /path/to/gems/line-bot-0.0.4/lib/line/bot/api.rb:24:in `perform_request'
    from /path/to/gems/line-bot-0.0.4/lib/line/bot/api.rb:16:in `perform_get_request'
    from /path/to/gems/line-bot-0.0.4/lib/line/bot/api/profile.rb:7:in `get_profiles'
    from test.rb:10:in `<main>'
```

However, there is no problem if run it with `bundle exec`.

```
$ bundle exec ruby test.rb
{:status=>200, :body=>{"contacts"=>[{"displayName"=>"....
```

You may have missed require "uri" in your gem code.

**Comment by gogotanaka** [comment]
@micat Thanks!（ありがとうございます！！）

This issue is fixed: https://github.com/aisaac-lab/line-bot/commit/cc095c9f5af2d0c982bd7b9a5df5747130e23e06

and released as v0.0.5 :)
